--
-- Author: Faizan Noor <admin@FaizanNoor.com>
-- URL: www.FaizanNoor.com
-- Description: List of all Languages of the world.

-- --------------------------------------------------------
--
-- Table structure for table `languages`
--

CREATE TABLE IF NOT EXISTS `languages` (
  `id` smallint(4) NOT NULL AUTO_INCREMENT,
  `name` varchar(24) NOT NULL,
  `iso2` char(2) DEFAULT NULL COMMENT 'ISO 639 alpha-2 code',
  `iso3` char(3) DEFAULT NULL COMMENT 'ISO 639 alpha-3 code',
  `native_name` varchar(144) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Active = 1, Inactive = 0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `languages_uq_name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

--
-- Dumping data for table `languages`
--

INSERT INTO `languages` (`id`, `name`, `iso2`, `iso3`, `native_name`, `is_active`) VALUES
(1, 'Abkhazian', 'ab', 'abk', 'Аҧсуа', 0),
(2, 'Afar', 'aa', 'aar', 'Afaraf', 0),
(3, 'Afrikaans', 'af', 'afr', 'Afrikaans', 0),
(4, 'Akan', 'ak', 'aka', 'Akan', 0),
(5, 'Albanian', 'sq', 'alb', 'Shqip', 0),
(6, 'Amharic', 'am', 'amh', 'አማርኛ', 0),
(7, 'Arabic', 'ar', 'ara', 'العربية', 0),
(8, 'Aragonese', 'an', 'arg', 'Aragonés', 0),
(9, 'Assamese', 'as', 'asm', 'অসমীয়া', 0),
(10, 'Armenian', 'hy', 'arm', 'Հայերեն', 0),
(11, 'Avaric', 'av', 'ava', 'авар мацӀ', 0),
(12, 'Avestan', 'ae', 'ave', 'avesta', 0),
(13, 'Aymara', 'ay', 'aym', 'aymar aru', 0),
(14, 'Azerbaijani', 'az', 'aze', 'azərbaycan dili', 0),
(15, 'Bashkir', 'ba', 'bak', 'башҡорт теле', 0),
(16, 'Bambara', 'bm', 'bam', 'bamanankan', 0),
(17, 'Basque', 'eu', 'baq', 'euskara', 0),
(18, 'Belarusian', 'be', 'bel', 'Беларуская', 0),
(19, 'Bengali', 'bn', 'ben', 'বাংলা', 0),
(20, 'Bihari', 'bh', 'bih', 'भोजपुरी', 0),
(21, 'Bislama', 'bi', 'bis', 'Bislama', 0),
(22, 'Bosnian', 'bs', 'bos', 'bosanski jezik', 0),
(23, 'Breton', 'br', 'bre', 'brezhoneg', 0),
(24, 'Bulgarian', 'bg', 'bul', 'български език', 0),
(25, 'Burmese', 'my', 'bur', 'ဗမာစာ', 0),
(26, 'Catalan; Valencian', 'ca', 'cat', 'Català', 0),
(27, 'Chamorro', 'ch', 'cha', 'Chamoru', 0),
(28, 'Chechen', 'ce', 'che', 'нохчийн мотт', 0),
(29, 'Chichewa', 'ny', 'nya', 'chinyanja', 0),
(30, 'Chinese', 'zh', 'chi', '"中文 (Zhōngwén), 汉语, 漢語"', 0),
(31, 'Chuvash', 'cv', 'chv', 'чӑваш чӗлхи', 0),
(32, 'Cornish', 'kw', 'cor', 'Kernewek', 0),
(33, 'Corsican', 'co', 'cos', 'corsu', 0),
(34, 'Cree', 'cr', 'cre', 'ᓀᐦᐃᔭᐍᐏᐣ', 0),
(35, 'Croatian', 'hr', 'hrv', 'hrvatski', 0),
(36, 'Czech', 'cs', 'cze', 'česky', 0),
(37, 'Danish', 'da', 'dan', 'dansk', 0),
(38, 'Maldivian', 'dv', 'div', 'ދިވެހި', 0),
(39, 'Dzongkha', 'dz', 'dzo', 'རྫོང་ཁ', 0),
(40, 'English', 'en', 'eng', 'English', 1),
(41, 'Esperanto', 'eo', 'epo', 'Esperanto', 0),
(42, 'Estonian', 'et', 'est', 'eesti', 0),
(43, 'Ewe', 'ee', 'ewe', 'Eʋegbe', 0),
(44, 'Faroese', 'fo', 'fao', 'føroyskt', 0),
(45, 'Fijian', 'fj', 'fij', 'vosa Vakaviti', 0),
(46, 'Finnish', 'fi', 'fin', 'suomi', 0),
(47, 'French', 'fr', 'fre', 'français', 0),
(48, 'Fula', 'ff', 'ful', 'Pular', 0),
(49, 'Galician', 'gl', 'glg', 'Galego', 0),
(50, 'German', 'de', 'ger', 'Deutsch', 0),
(51, 'Greek', 'el', 'gre', 'Ελληνικά', 0),
(52, 'Guaraní', 'gn', 'grn', 'Avañe''ẽ', 0),
(53, 'Gujarati', 'gu', 'guj', 'ગુજરાતી', 0),
(54, 'Haitian', 'ht', 'hat', 'Kreyòl ayisyen', 0),
(55, 'Hausa', 'ha', 'hau', '"Hausa, هَوُسَ"', 0),
(56, 'Hebrew', 'he', 'heb', 'עברית', 0),
(57, 'Herero', 'hz', 'her', 'Otjiherero', 0),
(58, 'Hindi', 'hi', 'hin', 'हिन्दी, हिंदी"', 0),
(59, 'Hiri Motu', 'ho', 'hmo', 'Hiri Motu', 0),
(60, 'Hungarian', 'hu', 'hun', 'Magyar', 0),
(61, 'Indonesian', 'id', 'ind', 'Bahasa Indonesia', 0),
(62, 'Irish', 'ga', 'gle', 'Gaeilge', 0),
(63, 'Igbo', 'ig', 'ibo', 'Igbo', 0),
(64, 'Inupiaq', 'ik', 'ipk', 'Iñupiaq', 0),
(65, 'Ido', 'io', 'ido', 'Ido', 0),
(66, 'Icelandic', 'is', 'ice', 'Íslenska', 0),
(67, 'Italian', 'it', 'ita', 'Italiano', 0),
(68, 'Inuktitut', 'iu', 'iku', 'ᐃᓄᒃᑎᑐᑦ', 0),
(69, 'Japanese', 'ja', 'jpn', '日本語', 0),
(70, 'Javanese', 'jv', 'jav', 'basa Jawa', 0),
(71, 'Georgian', 'ka', 'geo', 'ქართული', 0),
(72, 'Kongo', 'kg', 'kon', 'KiKongo', 0),
(73, 'Kazakh', 'kk', 'kaz', 'Қазақ тілі', 0),
(74, 'Central Khmer', 'km', 'khm', 'ភាសាខ្មែរ', 0),
(75, 'Kannada', 'kn', 'kan', 'ಕನ್ನಡ', 0),
(76, 'Korean', 'ko', 'kor', '韓國語', 0),
(77, 'Kanuri', 'kr', 'kau', 'Kanuri', 0),
(78, 'Kashmiri', 'ks', 'kas', '"कश्मीरी, كشميري‎"', 0),
(79, 'Kurdish', 'ku', 'kur', 'Kurdî', 0),
(80, 'Komi', 'kv', 'kom', 'коми кыв', 0),
(81, 'Kirghiz', 'ky', 'kir', 'кыргыз тили', 0),
(82, 'Latin', 'la', 'lat', 'latine', 0),
(83, 'Luxembourgish', 'lb', 'ltz', 'Lëtzebuergesch', 0),
(84, 'Luganda', 'lg', 'lug', 'Luganda', 0),
(85, 'Lingala', 'ln', 'lin', 'Lingála', 0),
(86, 'Lao', 'lo', 'lao', 'ພາສາລາວ', 0),
(87, 'Lithuanian', 'lt', 'lit', 'lietuvių kalba', 0),
(88, 'Luba-Katanga', 'lu', 'lub', '', 0),
(89, 'Latvian', 'lv', 'lav', 'latviešu valoda', 0),
(90, 'Malagasy', 'mg', 'mlg', 'Malagasy fiteny', 0),
(91, 'Marshallese', 'mh', 'mah', 'Kajin M̧ajeļ', 0),
(92, 'Manx', 'gv', 'glv', '"Gaelg, Gailck"', 0),
(93, 'Māori', 'mi', 'mao', 'te reo Māori', 0),
(94, 'Macedonian', 'mk', 'mac', 'македонски јазик', 0),
(95, 'Malayalam', 'ml', 'mal', 'മലയാളം', 0),
(96, 'Mongolian', 'mn', 'mon', 'Монгол', 0),
(97, 'Marathi', 'mr', 'mar', 'मराठी', 0),
(98, 'Malay', 'ms', 'may', '"bahasa Melayu, بهاس ملايو‎"', 0),
(99, 'Maltese', 'mt', 'mlt', 'Malti', 0),
(100, 'Nauru', 'na', 'nau', 'Ekakairũ Naoero', 0),
(101, 'North Ndebele', 'nd', 'nde', 'isiNdebele', 0),
(102, 'Nepali', 'ne', 'nep', 'नेपाली', 0),
(103, 'Ndonga', 'ng', 'ndo', 'Owambo', 0),
(104, 'Dutch', 'nl', 'dut', 'Nederlands', 0),
(105, 'Norwegian', 'no', 'nor', 'Norsk', 0),
(106, 'South Ndebele', 'nr', 'nbl', 'isiNdebele', 0),
(107, 'Navajo', 'nv', 'nav', 'Diné bizaad', 0),
(108, 'Oromo', 'om', 'orm', 'Afaan Oromoo', 0),
(109, 'Oriya', 'or', 'ori', 'ଓଡ଼ିଆ', 0),
(110, 'Ossetian', 'os', 'oss', 'Ирон æвзаг', 0),
(111, 'Punjabi', 'pa', 'pan', '"ਪੰਜਾਬੀ', 0),
(112, 'Pāli', 'pi', 'pli', 'पाऴि', 0),
(113, 'Persian', 'fa', 'per', 'فارسی', 0),
(114, 'Polish', 'pl', 'pol', 'polski', 0),
(115, 'Portuguese', 'pt', 'por', 'Português', 0),
(116, 'Quechua', 'qu', 'que', 'Kichwa', 0),
(117, 'Kirundi', 'rn', 'run', 'Rundi', 0),
(118, 'Romanian', 'ro', 'rum', 'română', 0),
(119, 'Russian', 'ru', 'rus', 'Русский язык', 0),
(120, 'Kinyarwanda', 'rw', 'kin', 'Ikinyarwanda', 0),
(121, 'Sanskrit', 'sa', 'san', 'संस्कृतम्', 0),
(122, 'Sardinian', 'sc', 'srd', 'sardu', 0),
(123, 'Sindhi', 'sd', 'snd', '"सिन्धी, سنڌي، سندھی‎"', 0),
(124, 'Northern Sami', 'se', 'sme', 'Davvisámegiella', 0),
(125, 'Samoan', 'sm', 'smo', 'gagana fa''a Samoa', 0),
(126, 'Sango', 'sg', 'sag', 'yângâ tî sängö', 0),
(127, 'Serbian', 'sr', 'srp', 'српски језик', 0),
(128, 'Gaelic', 'gd', 'gla', 'Gàidhlig', 0),
(129, 'Shona', 'sn', 'sna', 'chiShona', 0),
(130, 'Sinhala', 'si', 'sin', 'සිංහල', 0),
(131, 'Slovak', 'sk', 'slo', 'slovenčina', 0),
(132, 'Slovene', 'sl', 'slv', 'slovenščina', 0),
(133, 'Somali', 'so', 'som', 'Soomaaliga', 0),
(134, 'Southern Sotho', 'st', 'sot', 'Sesotho', 0),
(135, 'Sundanese', 'su', 'sun', 'Basa Sunda', 0),
(136, 'Swahili', 'sw', 'swa', 'Kiswahili', 0),
(137, 'Swati', 'ss', 'ssw', 'SiSwati', 0),
(138, 'Swedish', 'sv', 'swe', 'svenska', 0),
(139, 'Tamil', 'ta', 'tam', 'தமிழ்', 0),
(140, 'Telugu', 'te', 'tel', 'తెలుగు', 0),
(141, 'Tajik', 'tg', 'tgk', 'toğikī', 0),
(142, 'Thai', 'th', 'tha', 'ไทย', 0),
(143, 'Tigrinya', 'ti', 'tir', 'ትግርኛ', 0),
(144, 'Tibetan', 'bo', 'tib', 'བོད་ཡིག', 0),
(145, 'Turkmen', 'tk', 'tuk', 'Türkmen', 0),
(146, 'Tagalog', 'tl', 'tgl', 'Wikang Tagalog', 0),
(147, 'Tswana', 'tn', 'tsn', 'Setswana', 0),
(148, 'Tonga', 'to', 'ton', 'faka Tonga', 0),
(149, 'Turkish', 'tr', 'tur', 'Türkçe', 0),
(150, 'Tsonga', 'ts', 'tso', 'Xitsonga', 0),
(151, 'Tatar', 'tt', 'tat', 'tatarça', 0),
(152, 'Twi', 'tw', 'twi', 'Twi', 0),
(153, 'Tahitian', 'ty', 'tah', 'Reo Mā`ohi', 0),
(154, 'Uighur', 'ug', 'uig', 'Uyƣurqə', 0),
(155, 'Ukrainian', 'uk', 'ukr', 'Українська', 0),
(156, 'Urdu', 'ur', 'urd', 'اردو', 0),
(157, 'Uzbek', 'uz', 'uzb', 'O''zbek', 0),
(158, 'Venda', 've', 'ven', 'Tshivenḓa', 0),
(159, 'Vietnamese', 'vi', 'vie', 'Tiếng Việt', 0),
(160, 'Volapük', 'vo', 'vol', 'Volapük', 0),
(161, 'Walloon', 'wa', 'wln', 'Walon', 0),
(162, 'Welsh', 'cy', 'wel', 'Cymraeg', 0),
(163, 'Wolof', 'wo', 'wol', 'Wollof', 0),
(164, 'Xhosa', 'xh', 'xho', 'isiXhosa', 0),
(165, 'Yoruba', 'yo', 'yor', 'Yorùbá', 0),
(166, 'Zhuang', 'za', 'zha', 'Saw cuengh', 0),
(167, 'Zulu', 'zu', 'zul', 'isiZulu', 0),
(168, 'Spanish', 'es', 'spa', 'español', 0),
(169, 'Norwegian Bokmål', 'nb', 'nob', 'Riksmål', 0);
-- --------------------------------------------------------
